//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaverCarAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListPassenger
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public System.Data.Entity.Spatial.DbGeography PlaceUser { get; set; }
        public int TripID { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
    }
}
