//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaverCarAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListComment
    {
        public int id { get; set; }
        public int CommentID { get; set; }
        public int UserID { get; set; }
    
        public virtual DriverComment DriverComment { get; set; }
        public virtual User User { get; set; }
    }
}
