//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaverCarAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapPoint()
        {
            this.ListMapPoints = new HashSet<ListMapPoint>();
        }
    
        public int id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Point { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListMapPoint> ListMapPoints { get; set; }
    }
}
